---
name: Perl CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version: ['5.32', '5.34', '5.38']

    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Perl ${{ matrix.perl-version }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install dependencies
        run: |
          cpanm --quiet --notest ExtUtils::MakeMaker
          cpanm --installdeps --quiet --notest .

      - name: Run tests
        run: |
          perl Makefile.PL
          make test
